variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CACHIX_CACHE: jd91mzm2
  NUR_REPO: jd91mzm2

stages:
  - build
  - deploy

default:
  image: nixos/nix
  retry: 1
  before_script:
    - nix --version
    - nix-channel --update
    - nix-env -iA cachix -f https://cachix.org/api/v1/install
    - |
      if [ -n "${CACHIX_CACHE}" ] && [ -n "${CACHIX_SIGNING_KEY}"]; then
          cachix use "${CACHIX_CACHE}"
      fi

build:
  stage: build
  script:
    - nix-build ci.nix -A buildOutputs
    - nix eval -f default.nix 'lib'
    - nix eval -f default.nix 'modules'
    - nix eval -f default.nix 'overlays'

deploy:
  stage: deploy
  only:
    - master
    - gitlab-ci
  script:
    - nix-build ci.nix -A cacheOutputs | cachix push "${CACHIX_CACHE}"
    - nix-env -iA nixpkgs.curl
    - curl -XPOST "https://nur-update.herokuapp.com/update?repo=${NUR_REPO}"
