variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CACHIX_CACHE: jd91mzm2
  NUR_REPO: jd91mzm2

stages:
  - build
  - cache
  - update

default:
  image: nixos/nix
  retry: 1
  before_script: &default_script
    - nix --version
    - nix-channel --update
    - nix-env -iA cachix -f https://cachix.org/api/v1/install
    - |
      if [ -n "${CACHIX_CACHE}" ] && [ -n "${CACHIX_SIGNING_KEY}"]; then
          cachix use "${CACHIX_CACHE}"
      fi

# Build phase

build unstable:
  stage: build
  before_script: &unstable_script
    - nix-channel --add https://nixos.org/channels/nixos-unstable nixos
    - *default_script
  script:
    - nix-build ci.nix -A buildOutputs
    - nix eval -f default.nix 'lib'
    - nix eval -f default.nix 'modules'
    - nix eval -f default.nix 'hm-modules'

build stable:
  stage: build
  extends: build unstable
  before_script: &stable_script
    - nix-channel --add https://nixos.org/channels/nixos-19.09 nixos
    - *default_script

# Cache phase

cache unstable:
  stage: cache
  only:
    - master
    - gitlab-ci
  before_script: *unstable_script
  script:
    - nix-build ci.nix -A cacheOutputs | cachix push "${CACHIX_CACHE}"

cache stable:
  stage: cache
  extends: cache unstable
  before_script: *stable_script

# Update phase

update:
  stage: update
  before_script:
    - nix --version
  script:
    - nix-env -iA nixpkgs.curl
    - curl -XPOST "https://nur-update.herokuapp.com/update?repo=${NUR_REPO}"
