name: Build and Populate Cache

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    # Everyday at 03:55
    - cron: 55 3 * * *

env:
  NUR_REPO: federicoschonborn

jobs:
  build:
    name: Build (${{ matrix.system }} · ${{ matrix.channel }})
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
        system:
          - x86_64-linux
        channel:
          - nixos-23.05
          - nixos-unstable
          - nixpkgs-unstable
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ${{ matrix.runs-on }}
      system: ${{ matrix.system }}
      channel: ${{ matrix.channel }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger NUR update
        run: curl -XPOST https://nur-update.herokuapp.com/update?repo=${{ env.NUR_REPO }}

  build-small:
    name: Build (${{ matrix.system }} · ${{ matrix.channel }})
    needs: build
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
        system:
          - x86_64-linux
        channel:
          - nixos-23.05-small
          - nixos-unstable-small
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ${{ matrix.runs-on }}
      system: ${{ matrix.system }}
      channel: ${{ matrix.channel }}

  build-darwin:
    name: Build (${{ matrix.system }} · ${{ matrix.channel }})
    needs: build
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - macos-latest
        system:
          - x86_64-darwin
        channel:
          - nixpkgs-23.05-darwin
          - nixpkgs-unstable
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ${{ matrix.runs-on }}
      system: ${{ matrix.system }}
      channel: ${{ matrix.channel }}

  build-aarch64:
    name: Build (${{ matrix.system }} · ${{ matrix.channel }})
    needs: build
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
        system:
          - aarch64-linux
        channel:
          - nixos-23.05
          - nixos-unstable
          - nixpkgs-unstable
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ${{ matrix.runs-on }}
      system: ${{ matrix.system }}
      channel: ${{ matrix.channel }}

  build-aarch64-small:
    name: Build (${{ matrix.system }} · ${{ matrix.channel }})
    needs: build-aarch64
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
        system:
          - aarch64-linux
        channel:
          - nixos-23.05-small
          - nixos-unstable-small
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ${{ matrix.runs-on }}
      system: ${{ matrix.system }}
      channel: ${{ matrix.channel }}
