name: Build and Populate Cache

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    # Everyday at 03:55
    - cron: 55 3 * * *

env:
  NUR_REPO: federicoschonborn

jobs:
  build-nixpkgs-unstable:
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ubuntu-latest
      system: x86_64-linux
      channel: nixpkgs-unstable
    secrets: inherit

  build-nixos-unstable-small:
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ubuntu-latest
      system: x86_64-linux
      channel: nixos-unstable-small
    secrets: inherit
    needs: build-nixpkgs-unstable

  build-nixos-unstable:
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ubuntu-latest
      system: x86_64-linux
      channel: nixos-unstable
    secrets: inherit
    needs: build-nixos-unstable-small

  build-nixos-stable-small:
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ubuntu-latest
      system: x86_64-linux
      channel: nixos-23.05-small
    secrets: inherit
    needs: build-nixos-unstable

  build-nixos-stable:
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ubuntu-latest
      system: x86_64-linux
      channel: nixos-23.05
    secrets: inherit
    needs: build-nixos-stable-small

  build-nixpkgs-unstable-cross:
    strategy:
      matrix:
        system:
          - i686-linux
          - aarch64-linux
          - armv7l-linux
          - armv6l-linux
          - mipsel-linux
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ubuntu-latest
      system: ${{ matrix.system }}
      channel: nixpkgs-unstable
    secrets: inherit
    needs: build-nixpkgs-unstable

  build-nixos-unstable-small-cross:
    strategy:
      matrix:
        system:
          - i686-linux
          - aarch64-linux
          - armv7l-linux
          - armv6l-linux
          - mipsel-linux
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ubuntu-latest
      system: ${{ matrix.system }}
      channel: nixos-unstable
    secrets: inherit
    needs: [build-nixos-unstable-small, build-nixpkgs-unstable-cross]

  build-nixos-unstable-cross:
    strategy:
      matrix:
        system:
          - i686-linux
          - aarch64-linux
          - armv7l-linux
          - armv6l-linux
          - mipsel-linux
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ubuntu-latest
      system: ${{ matrix.system }}
      channel: nixos-unstable
    secrets: inherit
    needs: [build-nixos-unstable, build-nixos-unstable-small-cross]

  build-nixos-stable-small-cross:
    strategy:
      matrix:
        system:
          - i686-linux
          - aarch64-linux
          - armv7l-linux
          - armv6l-linux
          - mipsel-linux
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ubuntu-latest
      system: ${{ matrix.system }}
      channel: nixos-23.05
    secrets: inherit
    needs: [build-nixos-stable-small, build-nixos-unstable-cross]

  build-nixos-stable-cross:
    strategy:
      matrix:
        system:
          - i686-linux
          - aarch64-linux
          - armv7l-linux
          - armv6l-linux
          - mipsel-linux
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ubuntu-latest
      system: ${{ matrix.system }}
      channel: nixos-23.05
    secrets: inherit
    needs: [build-nixos-stable, build-nixos-stable-small-cross]

  build-nixpkgs-unstable-darwin:
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: macos-latest
      system: x86_64-darwin
      channel: nixpkgs-unstable
    secrets: inherit
    needs: build-nixpkgs-unstable

  build-nixos-stable-darwin:
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: macos-latest
      system: x86_64-darwin
      channel: nixpkgs-23.05-darwin
    secrets: inherit
    needs: [build-nixos-stable, build-nixpkgs-unstable-darwin]

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger NUR update
        run: curl -XPOST https://nur-update.herokuapp.com/update?repo=${{ env.NUR_REPO }}
    needs: build-nixos-stable
