name: Build and Populate Cache

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    # Everyday at 03:55
    - cron: 55 3 * * *

env:
  NUR_REPO: federicoschonborn

jobs:
  build-nixpkgs-unstable:
    name: Build (Unstable)
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ubuntu-latest
      system: x86_64-linux
      channel: nixpkgs-unstable

  build-nixpkgs-unstable-aarch64:
    name: Build (Unstable aarch64)
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ubuntu-latest
      system: aarch64-linux
      channel: nixpkgs-unstable

  build-nixos-unstable:
    name: Build (NixOS Unstable)
    needs: build-nixpkgs-unstable
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ubuntu-latest
      system: x86_64-linux
      channel: nixos-unstable

  build-nixos-unstable-aarch64:
    name: Build (NixOS Unstable aarch64)
    needs: build-nixpkgs-unstable-aarch64
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ubuntu-latest
      system: aarch64-linux
      channel: nixos-unstable

  build-stable:
    name: Build (Stable)
    needs: build-nixos-unstable
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ubuntu-latest
      system: x86_64-linux
      channel: nixos-23.05

  build-stable-aarch64:
    name: Build (Stable aarch64)
    needs: build-nixos-unstable-aarch64
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ubuntu-latest
      system: aarch64-linux
      channel: nixos-23.05

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-stable
    steps:
      - name: Trigger NUR update
        run: curl -XPOST https://nur-update.herokuapp.com/update?repo=${{ env.NUR_REPO }}
