name: Build and Populate Cache

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    # Everyday at 03:55
    - cron: 55 3 * * *

env:
  NUR_REPO: federicoschonborn

jobs:
  build-unstable:
    name: Build (Unstable)
    strategy:
      matrix:
        channel:
          - nixos-unstable
          - nixpkgs-unstable
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ubuntu-latest
      system: x86_64-linux
      channel: ${{ matrix.channel }}

  build-stable:
    name: Build (Stable)
    needs: build-unstable
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ubuntu-latest
      system: x86_64-linux
      channel: nixos-23.05

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-stable
    steps:
      - name: Trigger NUR update
        run: curl -XPOST https://nur-update.herokuapp.com/update?repo=${{ env.NUR_REPO }}

  build-darwin-unstable:
    name: Build (Darwin; Unstable)
    needs: build-unstable
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: macos-latest
      system: x86_64-darwin
      channel: nixpkgs-unstable

  build-darwin-stable:
    name: Build (Darwin; Stable)
    needs: build-darwin-unstable
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: macos-latest
      system: x86_64-darwin
      channel: nixpkgs-23.05-darwin

  build-aarch64-unstable:
    name: Build (AArch64; Unstable)
    needs: build-unstable
    strategy:
      matrix:
        channel:
          - nixos-unstable
          - nixpkgs-unstable
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ubuntu-latest
      system: aarch64-linux
      channel: ${{ matrix.channel }}

  build-aarch64-stable:
    name: Build (AArch64; Stable)
    needs: build-aarch64-unstable
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ubuntu-latest
      system: aarch64-linux
      channel: nixos-23.05
