- name: Criar pasta temporária onde deixar o symlink result
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  delegate_to: 127.0.0.1
  register: nixos_build_result
# - name: Mostrar a pasta temporária
#   ansible.builtin.debug:
#     msg: "Pasta temporária: {{ nixos_build_result.path }}"
- name: Build NixOS generation
  ansible.builtin.command:
    cmd: nix build {{ playbook_dir }}#nixosConfigurations.{{ ansible_facts['hostname'] }}.config.system.build.toplevel -o {{ nixos_build_result.path }}/result
  when: ansible_facts['os_family'] == "NixOS"
  delegate_to: 127.0.0.1
- name: Get NixOS generation output path
  ansible.builtin.command:
    cmd: "realpath {{ nixos_build_result.path }}/result"
  delegate_to: 127.0.0.1
  register: nixos_build_result_realpath_cmd
- name: Set NixOS build result
  set_fact:
    nixos_build_result: "{{ nixos_build_result_realpath_cmd.stdout }}"
  delegate_to: 127.0.0.1
# - name: Show NixOS build result path
#   ansible.builtin.debug:
#     msg: "System build path: {{ nixos_build_result }}"
