image: nixos/nix
stages: [build]

instantiation:
  stage: build
  script:
    # evaluation only, no artifacts -> no redistribution
    - export NIXPKGS_ALLOW_UNFREE=1
    - nix-instantiate gitlab-ci
    - nix-env -qa --json --file gitlab-ci
  artifacts:
    paths:
      - /nix/store/*.drv
