[bird-lg-go]
src.git = "https://github.com/xddxdd/bird-lg-go.git"
fetch.github = "xddxdd/bird-lg-go"

[boringssl-oqs]
src.github = "open-quantum-safe/boringssl"
fetch.github = "open-quantum-safe/boringssl"

[drone-vault]
src.github_tag = "drone/drone-vault"
fetch.github = "drone/drone-vault"

[glauth]
src.github = "glauth/glauth"
fetch.github = "glauth/glauth"

[hoyo-glyphs]
src.git = "https://github.com/SpeedyOrc-C/Hoyo-Glyphs.git"
fetch.github = "SpeedyOrc-C/Hoyo-Glyphs"

[konnect]
src.github_tag = "Kopano-dev/konnect"
fetch.github = "Kopano-dev/konnect"

[libltnginx]
src.git = "https://github.com/xddxdd/libltnginx.git"
fetch.github = "xddxdd/libltnginx"

[liboqs]
src.github = "open-quantum-safe/liboqs"
fetch.github = "open-quantum-safe/liboqs"

[netboot-xyz-efi]
src.github = "netbootxyz/netboot.xyz"
fetch.url = "https://github.com/netbootxyz/netboot.xyz/releases/download/$ver/netboot.xyz.efi"

[netboot-xyz-lkrn]
src.github = "netbootxyz/netboot.xyz"
fetch.url = "https://github.com/netbootxyz/netboot.xyz/releases/download/$ver/netboot.xyz.lkrn"

[netns-exec]
src.git = "https://github.com/pekman/netns-exec.git"
fetch.github = "pekman/netns-exec"
git.fetchSubmodules = true

[noise-suppression-for-voice]
src.github = "werman/noise-suppression-for-voice"
fetch.github = "werman/noise-suppression-for-voice"

[openssl-oqs]
src.github = "open-quantum-safe/openssl"
fetch.github = "open-quantum-safe/openssl"

[osdlyrics]
src.github = "osdlyrics/osdlyrics"
fetch.github = "osdlyrics/osdlyrics"

[phpmyadmin]
src.github_tag = "phpmyadmin/phpmyadmin"
src.include_regex = "RELEASE_([0-9_]*)"
src.from_pattern = "RELEASE_([0-9])_([0-9])_([0-9])"
src.to_pattern = "\\1.\\2.\\3"
fetch.url = "https://files.phpmyadmin.net/phpMyAdmin/$ver/phpMyAdmin-$ver-all-languages.tar.xz"

[phppgadmin]
src.github = "phppgadmin/phppgadmin"
fetch.github = "phppgadmin/phppgadmin"

[qbittorrent-enhanced-edition]
src.github = "c0re100/qBittorrent-Enhanced-Edition"
fetch.github = "c0re100/qBittorrent-Enhanced-Edition"

[rime-aurora-pinyin]
src.git = "https://github.com/hosxy/rime-aurora-pinyin.git"
fetch.github = "hosxy/rime-aurora-pinyin"

[rime-dict]
src.git = "https://github.com/Iorest/rime-dict.git"
fetch.github = "Iorest/rime-dict"

[rime-moegirl]
src.github = "outloudvi/mw2fcitx"
fetch.url = "https://github.com/outloudvi/mw2fcitx/releases/download/$ver/moegirl.dict.yaml"

[rime-zhwiki]
src.webpage = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases"
src.regex = "zhwiki-([0-9]{8})\\.dict\\.yaml"
fetch.url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-$ver.dict.yaml"

[route-chain]
src.git = "https://github.com/xddxdd/route-chain.git"
fetch.github = "xddxdd/route-chain"

[v2fly-geoip]
src.github = "v2fly/geoip"
fetch.url = "https://github.com/v2fly/geoip/releases/download/$ver/geoip.dat"

[v2fly-private]
src.github = "v2fly/geoip"
fetch.url = "https://github.com/v2fly/geoip/releases/download/$ver/private.dat"

[v2fly-geosite]
src.github = "v2fly/domain-list-community"
fetch.url = "https://github.com/v2fly/domain-list-community/releases/download/$ver/dlc.dat"

[xray]
src.github = "XTLS/Xray-core"
fetch.github = "XTLS/Xray-core"
