---
kind: pipeline
type: exec
name: NixOS config check

steps:
- name: format check
  commands:
  - nix develop -c nixpkgs-fmt .

- name: notifiy
  commands:
  - nix run .#matrix-notifier
  environment:
    ADDRESS:
      from_secret: matrix_homeserver
    ROOM:
      from_secret: matrix_roomid
    USER:
      from_secret: matrix_username
    PASS:
      from_secret: matrix_password
  when:
    status:
      - failure
      - success
...
