repos:
- repo: 'https://github.com/pre-commit/pre-commit-hooks'
  rev: 'v2.3.0'
  hooks:
  - id: 'trailing-whitespace'
  - id: 'end-of-file-fixer'
  - id: 'check-yaml'
  - id: 'check-added-large-files'
- repo: 'https://github.com/jumanjihouse/pre-commit-hooks'
  rev: '2.1.4'
  hooks:
  - id: 'forbid-binary'
- repo: 'local'
  hooks:
  - id: 'nixpkgs-fmt'
    name: 'nixpkgs-fmt'
    description: 'Format nix code with nixpkgs-fmt'
    entry: 'nixpkgs-fmt'
    language: 'system'
    files: '\.nix$'
    always_run: true
