image: nixos/20.09
repositories:
  nixpkgs: https://nixos.org/channels/nixos-20.09
packages:
  - nixpkgs.cachix
sources:
  - https://git.sr.ht/~priegger/nur-packages
secrets:
  -  979bc696-35ff-421b-a46e-99f04e657a87 # cachix-priegger
environment:
  CACHIX_CACHE: priegger
tasks:
  - setup: |
      cachix use "${CACHIX_CACHE}" --mode user-nixconf
  - lint: |
      cd nur-packages
      nix-shell -p nixpkgs-fmt -I nixpkgs=./nix --run "find . -name '*.nix' -exec nixpkgs-fmt --check {} +"
      nix-shell -p shellcheck -I nixpkgs=./nix --run "find . -name '*.sh' -exec shellcheck --shell bash {} +"
  - build: |
      cd nur-packages

      nix-build ci.nix -A buildOutputs
      nix eval -f nur.nix 'lib'
      nix eval -f nur.nix 'modules'
      nix eval -f nur.nix 'overlays'

      nix-build -E 'with import <nixpkgs>{}; (callPackage ./default.nix {})'
  - test: |
      cd nur-packages
      for test in tests/*.nix; do nix-build --no-out-link "${test}"; done
  - deploy: |
      cd nur-packages
      [ "$(git rev-parse HEAD)" == "$(git rev-parse master)" ] || complete-build
      nix-build ci.nix -A cacheOutputs | cachix push "${CACHIX_CACHE}"
triggers:
  - action: email
    condition: failure
    to: Philipp Riegger <philipp@riegger.name>