image: nixos/unstable
packages:
  - nixos.cachix
  - nixos.nixpkgs-fmt
  - nixos.shellcheck
sources:
  - https://git.sr.ht/~priegger/nur-packages
secrets:
  -  979bc696-35ff-421b-a46e-99f04e657a87 # cachix-priegger
environment:
  CACHIX_CACHE: priegger
  NUR_REPO: priegger
tasks:
  - setup: |
      set -o pipefail
      cachix use "${CACHIX_CACHE}" --mode user-nixconf
      nix path-info --all | grep -v '\.drv$' >store-path-pre-build
      nohup cachix push --watch-store "${CACHIX_CACHE}" </dev/null >cachix.out 2>cachix.err &
      sleep 1
  - lint: |
      cd nur-packages
      find . -name '*.nix' -exec nixpkgs-fmt --check {} +
      find . -name '*.sh' -exec shellcheck --shell bash {} +
  - build: |
      cd nur-packages

      nix-build ci.nix -A buildOutputs

      nix eval -f nur.nix 'lib'
      nix eval -f nur.nix 'modules'
      nix eval -f nur.nix 'overlays'

      nix-build -E 'with import <nixpkgs>{}; (callPackage ./default.nix {})'
  - test: |
      cd nur-packages
      for test in tests/*.nix; do nix-build --no-out-link "${test}"; done
  - teardown: |
      set -o pipefail
      comm -13 <(sort store-path-pre-build) <(nix path-info --all | grep -v '\.drv$' | sort) | cachix push -j2 "${CACHIX_CACHE}"
  - deploy: |
      cd nur-packages
      [ "$(git rev-parse HEAD)" = "$(git rev-parse master)" ] || complete-build
      curl -XPOST "https://nur-update.herokuapp.com/update?repo=${NUR_REPO}"
artifacts:
  - cachix.out
  - cachix.err
triggers:
  - action: email
    condition: failure
    to: Philipp Riegger <philipp@riegger.name>
