name: Publish

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"

jobs:
  iso:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        image:
          - bootstrap
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v26
        with:
          nix_conf: |
            accept-flake-config = true
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: |
          nix build .#nixosConfigurations.${{ matrix.image }}.config.system.build.isoImage
          cp result/iso/${{ matrix.image }}-*.iso ${{ matrix.image }}.iso
          sha256sum ${{ matrix.image }}.iso > ${{ matrix.image }}.iso.sha256sum
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ matrix.image }}.iso
            ${{ matrix.image }}.iso.sha256sum
  flakehub:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: "actions/checkout@v4"
        with:
          ref: "${{ (inputs.tag != null) && format('refs/tags/{0}', inputs.tag) || '' }}"
      - uses: "DeterminateSystems/nix-installer-action@v9"
      - uses: "DeterminateSystems/flakehub-push@v3"
        with:
          visibility: "public"
          tag: "${{ inputs.tag }}"
          name: "UnidealisticRaccoon/SnowyBurrow"
