name: "Publish"

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"

jobs:
  flakehub:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: "actions/checkout@v4"
        with:
          ref: "${{ (inputs.tag != null) && format('refs/tags/{0}', inputs.tag) || '' }}"
      - uses: "DeterminateSystems/nix-installer-action@v9"
      - uses: "DeterminateSystems/flakehub-push@v3"
        with:
          visibility: "public"
          tag: "${{ inputs.tag }}"
          name: "UnidealisticRaccoon/SnowyBurrow"
