name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release-please.outputs.tag_name }}
      releases_created: ${{ steps.release-please.outputs.releases_created }}
    steps:
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: google-github-actions/release-please-action@v4
        id: release-please
        with:
          release-type: simple
          token: ${{ steps.generate-token.outputs.token }}
  iso:
    if: needs.tag.outputs.releases_created
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        image:
          - bootstrap
    steps:
      - uses: "actions/checkout@v4"
      - uses: "DeterminateSystems/nix-installer-action@v9"
      - name: Upload ISOs
        if: ${{ steps.tag.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          nix build .#nixosConfigurations.${{ matrix.image }}.config.system.build.isoImage
          cp result/iso/nixos.iso ${{ matrix.image }}.iso
          gh release upload \
            ${{ needs.tag.outputs.tag }} \
            ${{ matrix.image }}.iso \
            --repo ${{ github.repository_owner }}/${{ github.event.repository.name }} \
            --clobber
