pipeline:
  verify:
    when:
      event: [ pull_request ]
    image: nixos/nix:2.8.0
    environment:
    - NIXPKGS_ALLOW_UNFREE=1
    commands:
    - nix --version
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
    - nix flake check path:. --impure

  update_nur:
    when:
      event: [ push ]
      branch: main
    image: nixos/nix:2.8.0
    environment:
    - NUR_REPO=wolfangaukang
    commands:
    - curl -XPOST "https://nur-update.herokuapp.com/update?repo=$NUR_REPO"
