version: 2

jobs:
  # ATTN: when you change anything here, don’t forget to copy it to the build-darwin section
  build-linux:
    docker:
      - image: nixos/nix:2.2.1
    working_directory: ~/lorri
    steps:
      - checkout
      - run:
          name: System dependencies
          command: |
            apk --no-progress update
            apk --no-progress add bash ca-certificates
            nix-channel --update
            # CircleCI and Nix sandboxing don't play nice. See
            # https://discourse.nixos.org/t/nixos-on-ovh-kimsufi-cloning-builder-process-operation-not-permitted/1494/5
            mkdir -p /etc/nix && echo "sandbox = false" > /etc/nix/nix.conf
      - run:
          name: cargo build & linters
          command: |
            nix-shell --run ci_check
      - run:
          name: nix build
          command: |
            nix-env -iA nixpkgs.git
            nix-build
            nix-env -i ./result
            lorri self-upgrade local $(pwd)

  build-darwin:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Install Nix
          command: |
            curl https://nixos.org/nix/install | sh
      - run:
          name: cargo build & linters
          shell: /bin/bash -eilo pipefail
          command: |
            nix-shell --run ci_check
      - run:
          name: nix build
          shell: /bin/bash -eilo pipefail
          command: |
            nix-env -iA nixpkgs.git
            nix-build
            nix-env -i ./result
            lorri self-upgrade local $(pwd)

workflows:
  version: 2
  build:
    jobs:
      - build-linux
      - build-darwin
