name: "Build and populate cache"
on:
  pull_request:
  push:
  schedule:
    # Random time so not all repositories are build at once:
    - cron: "10 1 * * *"
jobs:
  tests:
    strategy:
      matrix:
        nurRepo:
          - j-k
        cachixName:
          - j-k-nur
        nixPath:
          - nixpkgs=channel:nixos-unstable
          - nixpkgs=channel:nixpkgs-unstable
          - nixpkgs=channel:nixos-20.09
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: "${{ matrix.nixPath }}"
      - name: Show nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
      - name: Setup cachix
        uses: cachix/cachix-action@v8
        if: ${{ matrix.cachixName == 'j-k-nur' }}
        with:
          name: ${{ matrix.cachixName }}
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: Check evaluation
        run: |
          nix-env -f . -qa \* --meta --xml \
            --allowed-uris https://static.rust-lang.org \
            --option restrict-eval true \
            --option allow-import-from-derivation true \
            --drv-path --show-trace \
            -I nixpkgs=$(nix-instantiate --find-file nixpkgs) \
            -I $PWD
      - name: Build nix packages
        run: nix run -I 'nixpkgs=channel:nixos-20.09' nixpkgs.nix-build-uncached -c nix-build-uncached ci.nix -A cacheOutputs
      - name: Trigger NUR update
        if: ${{ matrix.nurRepo == 'j-k' }}
        run: curl -XPOST "https://nur-update.herokuapp.com/update?repo=${{ matrix.nurRepo }}"
